apiVersion: apps/v1
kind: Deployment
metadata:
  name: mud-server
  namespace: games
  labels:
    app.kubernetes.io/instance: mud
    app.kubernetes.io/name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: mud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: mud
    spec:
      containers:
        - name: mud
          image: ghcr.io/pixil98/mud:v0.0.2
          imagePullPolicy: IfNotPresent
          command: ["/app/mud"]
          args: ["--config", "/app/config.json"]
          ports:
            - name: telnet
              containerPort: 4000
              protocol: TCP
          volumeMounts:
            - name: characters
              mountPath: /app/assets/characters
      volumes:
        - name: characters
          persistentVolumeClaim:
            claimName: mud-server-characters
